/**
 * Database types for the public schema.
 *
 * Hand-written to match supabase/migrations/0001_init.sql. Regenerate via
 *   npx supabase gen types typescript --project-id gdinummzvbwjfdesqfpt
 * once a personal access token is set (`supabase login` or
 * SUPABASE_ACCESS_TOKEN env var).
 *
 * Conventions:
 * - All `id` columns are TEXT (uuid v4 strings generated by the app).
 * - Timestamps are ISO strings as returned by PostgREST.
 * - `numeric` columns come back as `number` from supabase-js v2.
 * - JSONB columns are typed as the embedded shapes used in src/lib/dev-store/*.
 */

// -----------------------------------------------------------------------------
// JSONB sub-shapes (mirror dev-store types so adapters can pass straight through)
// -----------------------------------------------------------------------------

export type ProjectTaskRow = {
    id: string;
    title: string;
    done: boolean;
    assignee: string;
    phase: string;
    createdAt: string;
};

export type ProjectDeliverableRow = {
    id: string;
    title: string;
    url: string;
    notes: string;
    phase: string;
    approvedAt: string | null;
    approvedBy: string;
    createdAt: string;
};

export type ProjectSignoffRow = {
    signedAt: string | null;
    signedBy: string;
    notes: string;
};

export type OnboardingFileRow = {
    name: string;
    size: number;
    type: string;
    url: string;
};

export type AuditChangeRow = {
    field: string;
    before: unknown;
    after: unknown;
};

// -----------------------------------------------------------------------------
// Per-table Row tuples (Insert/Update default to Partial<Row>)
// -----------------------------------------------------------------------------

type Tbl<R> = {
    Row: R;
    Insert: Partial<R> & { id?: string };
    Update: Partial<R>;
    Relationships: [];
};

export type AgencyProfileRow = {
    id: string;
    legal_name: string;
    display_name: string;
    registration_no: string;
    sst_no: string;
    email: string;
    phone: string;
    website_url: string;
    address_line1: string;
    address_line2: string;
    city: string;
    state: string;
    postcode: string;
    country: string;
    bank_name: string;
    bank_account_name: string;
    bank_account_no: string;
    invoice_footer: string;
    updated_at: string;
};

export type ServiceRow = {
    id: string;
    name: string;
    category: string;
    unit: string;
    default_price: number;
    description: string;
    active: boolean;
    created_at: string;
    updated_at: string;
};

export type ClientRow = {
    id: string;
    name: string;
    status: string;
    contact_name: string;
    contact_email: string;
    contact_phone: string;
    website: string;
    industry: string;
    notes: string;
    content_revision_limit: number;
    monthly_content_quota: number;
    portal_token: string;
    user_id: string | null;
    created_at: string;
    updated_at: string;
};

export type TeamMemberRow = {
    id: string;
    name: string;
    role: string;
    email: string;
    phone: string;
    skills: string;
    active: boolean;
    user_id: string | null;
    created_at: string;
    updated_at: string;
};

export type LeadRow = {
    id: string;
    name: string;
    company: string;
    email: string;
    phone: string;
    source: string;
    source_campaign_id: string | null;
    interested_in: string;
    est_value_myr: number;
    status: string;
    notes: string;
    onboarding_submission_id: string | null;
    assigned_to: string;
    score: number;
    created_at: string;
    updated_at: string;
};

export type OnboardingSubmissionRow = {
    id: string;
    token: string;
    checklist_slug: string;
    client_name: string;
    status: string;
    data: Record<string, unknown>;
    files: Record<string, OnboardingFileRow | OnboardingFileRow[]>;
    notes: string;
    created_at: string;
    updated_at: string;
    submitted_at: string | null;
};

export type ProjectStageRow = {
    id: string;
    label: string;
    ownerRole: string;
    assignee: string;
    state: "pending" | "active" | "done";
    startedAt: string | null;
    doneAt: string | null;
};

export type ProjectRow = {
    id: string;
    name: string;
    client_name: string;
    status: string;
    phase: string;
    service_category: string;
    onboarding_submission_id: string | null;
    notes: string;
    tasks: ProjectTaskRow[];
    deliverables: ProjectDeliverableRow[];
    stages: ProjectStageRow[];
    signoff: ProjectSignoffRow;
    portal_token: string;
    created_at: string;
    updated_at: string;
};

export type WorkflowStageDefRow = {
    key: string;
    label: string;
    ownerRole: string;
    description: string;
};

export type WorkflowTemplateRow = {
    service_category: string;
    name: string;
    stages: WorkflowStageDefRow[];
    updated_at: string;
};

export type InvoiceRow = {
    id: string;
    number: string;
    client_name: string;
    project_id: string | null;
    status: string;
    issue_date: string;
    due_date: string;
    tax_rate_pct: number;
    notes: string;
    created_at: string;
    updated_at: string;
    paid_at: string | null;
    // Payment-link metadata (added by migration 0003)
    payment_provider: string | null;
    payment_link: string | null;
    payment_external_id: string | null;
    payment_meta: Record<string, unknown>;
    payment_link_created_at: string | null;
};

export type InvoiceItemRow = {
    id: string;
    invoice_id: string;
    description: string;
    quantity: number;
    unit_price_myr: number;
    sort_order: number;
};

export type CampaignRow = {
    id: string;
    name: string;
    client_name: string;
    platform: string;
    objective: string;
    status: string;
    start_date: string | null;
    end_date: string | null;
    monthly_budget_myr: number;
    fee_model: string;
    flat_fee_myr: number;
    percent_fee: number;
    external_id: string;
    landing_url: string;
    notes: string;
    created_at: string;
    updated_at: string;
};

export type CampaignMetricRow = {
    id: string;
    campaign_id: string;
    date: string;
    spend_myr: number;
    impressions: number;
    clicks: number;
    leads_reported: number;
    conversions_reported: number;
    notes: string;
    entered_by: string;
    created_at: string;
};

export type ContentDraftRow = {
    id: string;
    draftNumber: string;
    fileUrl: string;
    caption: string;
    submittedAt: string;
    submittedBy: string;
};

export type ContentFeedbackRow = {
    id: string;
    draftId: string;
    author: "client" | "agency";
    body: string;
    fileUrl: string;
    cycle: number;
    createdAt: string;
};

export type ContentPostRow = {
    id: string;
    title: string;
    client_name: string;
    project_id: string | null;
    platform: string;
    type: string;
    status: string;
    scheduled_for: string;
    scheduled_time: string;
    caption: string;
    hashtags: string;
    notes: string;
    assignee: string;
    plan_month: string;
    origin: string;
    review_status: string;
    draft_number: string;
    revisions_used: number;
    current_file_url: string;
    drafts: ContentDraftRow[];
    feedback: ContentFeedbackRow[];
    approved_at: string | null;
    approved_by: string;
    created_at: string;
    updated_at: string;
    posted_at: string | null;
};

export type SeoArticleRow = {
    id: string;
    title: string;
    client_name: string;
    target_keyword: string;
    secondary_keywords: string;
    search_intent: string;
    target_word_count: number;
    brief: string;
    outline: string;
    body: string;
    published_url: string;
    stage: string;
    assignee: string;
    target_date: string | null;
    created_at: string;
    updated_at: string;
    published_at: string | null;
};

export type NotificationRow = {
    id: string;
    kind: string;
    title: string;
    body: string;
    link: string;
    created_at: string;
    read_at: string | null;
};

export type AuditEventRow = {
    id: string;
    at: string;
    entity: string;
    entity_id: string;
    kind: string;
    summary: string;
    actor: string;
    changes: AuditChangeRow[];
};

// -----------------------------------------------------------------------------
// Database type expected by supabase-js
// -----------------------------------------------------------------------------

export type Database = {
    public: {
        Tables: {
            agency_profile: Tbl<AgencyProfileRow>;
            services: Tbl<ServiceRow>;
            clients: Tbl<ClientRow>;
            team_members: Tbl<TeamMemberRow>;
            leads: Tbl<LeadRow>;
            onboarding_submissions: Tbl<OnboardingSubmissionRow>;
            projects: Tbl<ProjectRow>;
            workflow_templates: Tbl<WorkflowTemplateRow>;
            invoices: Tbl<InvoiceRow>;
            invoice_items: Tbl<InvoiceItemRow>;
            campaigns: Tbl<CampaignRow>;
            campaign_metrics: Tbl<CampaignMetricRow>;
            content_posts: Tbl<ContentPostRow>;
            seo_articles: Tbl<SeoArticleRow>;
            notifications: Tbl<NotificationRow>;
            audit_events: Tbl<AuditEventRow>;
        };
        Views: Record<string, never>;
        // Permissive Functions map: the new schema declares no RPCs yet, but
        // legacy code still calls `supabase.rpc("user_has_permission", …)`
        // behind a DEV_AUTH_BYPASS guard. Loose typing keeps the call site
        // compiling until permissions land in I1.15.
        Functions: {
            [name: string]: {
                Args: Record<string, unknown>;
                Returns: unknown;
            };
        };
        Enums: Record<string, never>;
        CompositeTypes: Record<string, never>;
    };
};
