-- =============================================================================
-- 0001_init.sql — Nexov Admin consolidated schema
-- =============================================================================
-- Apply with:  supabase db push  (or `supabase db reset` for a fresh DB)
--
-- Mirrors the shape of src/lib/dev-store/* exactly. The TypeScript adapters in
-- src/lib/data/* translate snake_case <-> camelCase; everything else lines up
-- 1:1 (same enum values, same field names).
--
-- Identity: every table uses `id text` (uuid v4 generated by the app) so dev
-- data can be seeded without re-keying. ON DELETE CASCADE only where children
-- have no meaning without the parent (invoice_items, campaign_metrics).
--
-- RLS: enabled on every public table. Policy = "authenticated can do anything"
-- for now (single-CEO tenant via DEV_AUTH_BYPASS or magic-link). Real
-- multi-tenant policies arrive when team auth lands.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- AGENCY PROFILE  (singleton row, id='nexov')
-- -----------------------------------------------------------------------------
create table public.agency_profile (
    id                   text primary key default 'nexov',
    legal_name           text not null default '',
    display_name         text not null default '',
    registration_no      text not null default '',
    sst_no               text not null default '',
    email                text not null default '',
    phone                text not null default '',
    website_url          text not null default '',
    address_line1        text not null default '',
    address_line2        text not null default '',
    city                 text not null default '',
    state                text not null default '',
    postcode             text not null default '',
    country              text not null default 'Malaysia',
    bank_name            text not null default '',
    bank_account_name    text not null default '',
    bank_account_no      text not null default '',
    invoice_footer       text not null default '',
    updated_at           timestamptz not null default now(),
    constraint agency_profile_singleton check (id = 'nexov')
);

-- -----------------------------------------------------------------------------
-- SERVICES (catalog)
-- -----------------------------------------------------------------------------
create table public.services (
    id              text primary key,
    name            text not null,
    category        text not null check (category in
                        ('website','ads','seo','content','app','branding','retainer','other')),
    unit            text not null default 'project',
    default_price   numeric(12,2) not null default 0,
    description     text not null default '',
    active          boolean not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- CLIENTS (agency's customers — identity by `name` to match clientName usage)
-- -----------------------------------------------------------------------------
create table public.clients (
    id              text primary key,
    name            text not null unique,
    status          text not null check (status in
                        ('prospect','active','paused','churned')) default 'prospect',
    contact_name    text not null default '',
    contact_email   text not null default '',
    contact_phone   text not null default '',
    website         text not null default '',
    industry        text not null default '',
    notes           text not null default '',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- TEAM MEMBERS
-- -----------------------------------------------------------------------------
create table public.team_members (
    id          text primary key,
    name        text not null,
    role        text not null check (role in
                    ('CEO','Closer','Frontend','Backend','UI/UX','Content','Ads','SEO','PM','Other')) default 'Other',
    email       text not null default '',
    phone       text not null default '',
    skills      text not null default '',
    active      boolean not null default true,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- LEADS
-- -----------------------------------------------------------------------------
create table public.leads (
    id                          text primary key,
    name                        text not null,
    company                     text not null default '',
    email                       text not null default '',
    phone                       text not null default '',
    source                      text not null check (source in
                                    ('referral','website','instagram','facebook','tiktok',
                                     'google','linkedin','event','cold_outreach','other')) default 'other',
    source_campaign_id          text,
    interested_in               text not null default '',
    est_value_myr               numeric(12,2) not null default 0,
    status                      text not null check (status in
                                    ('new','contacted','qualified','proposal','won','lost')) default 'new',
    notes                       text not null default '',
    onboarding_submission_id    text,
    assigned_to                 text not null default '',
    score                       int not null default 0,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);
create index leads_status_idx on public.leads (status);
create index leads_source_idx on public.leads (source);
create index leads_assigned_idx on public.leads (assigned_to);

-- -----------------------------------------------------------------------------
-- ONBOARDING SUBMISSIONS
-- -----------------------------------------------------------------------------
create table public.onboarding_submissions (
    id              text primary key,
    token           text not null unique,
    checklist_slug  text not null default 'website-creation',
    client_name     text not null,
    status          text not null check (status in ('draft','submitted')) default 'draft',
    data            jsonb not null default '{}'::jsonb,
    files           jsonb not null default '{}'::jsonb,
    notes           text not null default '',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    submitted_at    timestamptz
);
create index onboarding_token_idx on public.onboarding_submissions (token);

-- -----------------------------------------------------------------------------
-- PROJECTS  (tasks/deliverables embedded as jsonb arrays — matches dev-store)
-- -----------------------------------------------------------------------------
create table public.projects (
    id                          text primary key,
    name                        text not null,
    client_name                 text not null,
    status                      text not null check (status in
                                    ('kickoff','in_progress','review','delivered','on_hold')) default 'kickoff',
    phase                       text not null check (phase in
                                    ('discovery','design','build','qa','client_review','launch','closed')) default 'discovery',
    onboarding_submission_id    text,
    notes                       text not null default '',
    tasks                       jsonb not null default '[]'::jsonb,
    deliverables                jsonb not null default '[]'::jsonb,
    signoff                     jsonb not null default
                                    '{"signedAt":null,"signedBy":"","notes":""}'::jsonb,
    portal_token                text not null default '',
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);
create index projects_client_idx on public.projects (client_name);
create index projects_status_idx on public.projects (status);
-- Portal token must be unique when present (empty allowed).
create unique index projects_portal_token_idx
    on public.projects (portal_token)
    where portal_token <> '';

-- -----------------------------------------------------------------------------
-- INVOICES + ITEMS
-- -----------------------------------------------------------------------------
create table public.invoices (
    id              text primary key,
    number          text not null unique,        -- e.g. INV-2026-0001
    client_name     text not null,
    project_id      text references public.projects(id) on delete set null,
    status          text not null check (status in
                        ('draft','sent','paid','overdue','void')) default 'draft',
    issue_date      date not null,
    due_date        date not null,
    tax_rate_pct    numeric(5,2) not null default 6,
    notes           text not null default '',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    paid_at         timestamptz
);
create index invoices_status_idx on public.invoices (status);
create index invoices_client_idx on public.invoices (client_name);

create table public.invoice_items (
    id                  text primary key,
    invoice_id          text not null references public.invoices(id) on delete cascade,
    description         text not null default '',
    quantity            numeric(12,2) not null default 1,
    unit_price_myr      numeric(12,2) not null default 0,
    -- Preserve insertion order without timestamps in the dev-store shape.
    sort_order          int not null default 0
);
create index invoice_items_invoice_idx on public.invoice_items (invoice_id);

-- -----------------------------------------------------------------------------
-- AD CAMPAIGNS + METRICS
-- -----------------------------------------------------------------------------
create table public.campaigns (
    id                      text primary key,
    name                    text not null,
    client_name             text not null,
    platform                text not null check (platform in
                                ('meta','google','tiktok','linkedin','x','youtube','other')),
    objective               text not null check (objective in
                                ('leads','sales','traffic','awareness','engagement','app_installs')),
    status                  text not null check (status in
                                ('planning','live','paused','ended')) default 'planning',
    start_date              date,
    end_date                date,
    monthly_budget_myr      numeric(12,2) not null default 0,
    fee_model               text not null check (fee_model in
                                ('none','flat','percent','flat_plus_percent')) default 'none',
    flat_fee_myr            numeric(12,2) not null default 0,
    percent_fee             numeric(5,2) not null default 0,
    external_id             text not null default '',
    landing_url             text not null default '',
    notes                   text not null default '',
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now()
);
create index campaigns_client_idx on public.campaigns (client_name);
create index campaigns_status_idx on public.campaigns (status);

create table public.campaign_metrics (
    id                          text primary key,
    campaign_id                 text not null references public.campaigns(id) on delete cascade,
    date                        date not null,
    spend_myr                   numeric(12,2) not null default 0,
    impressions                 bigint not null default 0,
    clicks                      bigint not null default 0,
    leads_reported              int not null default 0,
    conversions_reported        int not null default 0,
    notes                       text not null default '',
    entered_by                  text not null check (entered_by in
                                    ('manual','meta_api','google_api','tiktok_api')) default 'manual',
    created_at                  timestamptz not null default now()
);
create index campaign_metrics_campaign_date_idx
    on public.campaign_metrics (campaign_id, date);

-- Foreign key for lead.source_campaign_id (deferred — campaigns table didn't
-- exist when leads was created above).
alter table public.leads
    add constraint leads_source_campaign_fk
    foreign key (source_campaign_id)
    references public.campaigns(id) on delete set null;

-- -----------------------------------------------------------------------------
-- CONTENT POSTS (social calendar)
-- -----------------------------------------------------------------------------
create table public.content_posts (
    id              text primary key,
    title           text not null,
    client_name     text not null,
    project_id      text references public.projects(id) on delete set null,
    platform        text not null check (platform in
                        ('instagram','facebook','tiktok','linkedin','x','youtube',
                         'blog','newsletter','gmb')) default 'instagram',
    type            text not null check (type in
                        ('post','reel','story','carousel','article','email','video')) default 'post',
    status          text not null check (status in
                        ('idea','draft','review','scheduled','posted','archived')) default 'idea',
    scheduled_for   date not null,
    scheduled_time  text not null default '',
    caption         text not null default '',
    hashtags        text not null default '',
    notes           text not null default '',
    assignee        text not null default '',
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    posted_at       timestamptz
);
create index content_posts_client_idx on public.content_posts (client_name);
create index content_posts_status_idx on public.content_posts (status);
create index content_posts_scheduled_idx on public.content_posts (scheduled_for);

-- -----------------------------------------------------------------------------
-- SEO ARTICLES (long-form workflow)
-- -----------------------------------------------------------------------------
create table public.seo_articles (
    id                      text primary key,
    title                   text not null,
    client_name             text not null,
    target_keyword          text not null default '',
    secondary_keywords      text not null default '',
    search_intent           text not null default '',
    target_word_count       int not null default 0,
    brief                   text not null default '',
    outline                 text not null default '',
    body                    text not null default '',
    published_url           text not null default '',
    stage                   text not null check (stage in
                                ('brief','outline','draft','review','published','archived')) default 'brief',
    assignee                text not null default '',
    target_date             date,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    published_at            timestamptz
);
create index seo_articles_client_idx on public.seo_articles (client_name);
create index seo_articles_stage_idx on public.seo_articles (stage);

-- -----------------------------------------------------------------------------
-- NOTIFICATIONS  (in-app inbox; single-tenant for now)
-- -----------------------------------------------------------------------------
create table public.notifications (
    id          text primary key,
    kind        text not null check (kind in
                    ('lead_new','lead_won','lead_lost','deliverable_approved',
                     'project_signoff','invoice_issued','invoice_paid','invoice_overdue',
                     'onboarding_submitted','system')),
    title       text not null,
    body        text not null default '',
    link        text not null default '',
    created_at  timestamptz not null default now(),
    read_at     timestamptz
);
create index notifications_unread_idx on public.notifications (read_at) where read_at is null;
create index notifications_created_idx on public.notifications (created_at desc);

-- -----------------------------------------------------------------------------
-- AUDIT EVENTS  (per-record change trail)
-- -----------------------------------------------------------------------------
create table public.audit_events (
    id          text primary key,
    at          timestamptz not null default now(),
    entity      text not null check (entity in ('lead','project','invoice','campaign')),
    entity_id   text not null,
    kind        text not null check (kind in ('create','update','status','delete')),
    summary     text not null,
    actor       text not null default '',
    -- Array of {field, before, after} objects.
    changes     jsonb not null default '[]'::jsonb
);
create index audit_entity_idx on public.audit_events (entity, entity_id, at desc);
create index audit_at_idx on public.audit_events (at desc);

-- =============================================================================
-- ROW-LEVEL SECURITY
-- =============================================================================
-- Single-CEO tenant: any authenticated user can read/write everything.
-- When team auth + roles arrive, replace these with per-role policies.
-- The `service_role` key bypasses RLS automatically (used for webhooks/seed).

do $$
declare
    t text;
    tables text[] := array[
        'agency_profile','services','clients','team_members','leads',
        'onboarding_submissions','projects','invoices','invoice_items',
        'campaigns','campaign_metrics','content_posts','seo_articles',
        'notifications','audit_events'
    ];
begin
    foreach t in array tables loop
        execute format('alter table public.%I enable row level security', t);
        execute format(
            'create policy %I on public.%I for all to authenticated using (true) with check (true)',
            t || '_authenticated_all', t
        );
    end loop;
end $$;

-- =============================================================================
-- AUTOMATIC updated_at maintenance
-- =============================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end $$;

do $$
declare
    t text;
    tables text[] := array[
        'agency_profile','services','clients','team_members','leads',
        'onboarding_submissions','projects','invoices','campaigns',
        'content_posts','seo_articles'
    ];
begin
    foreach t in array tables loop
        execute format(
            'create trigger %I before update on public.%I
             for each row execute function public.set_updated_at()',
            t || '_set_updated_at', t
        );
    end loop;
end $$;

-- =============================================================================
-- SEED: agency profile singleton row
-- =============================================================================
insert into public.agency_profile (id) values ('nexov')
on conflict (id) do nothing;
